#!/usr/bin/fish

function link -a target link_name
  if begin; test -e $link_name; and not test -L $link_name; end
    echo (set_color red)"Cannot create a symlink from $link_name. File already exists"
  else
    echo (set_color normal)"Linking $link_name -> $target"
    ln -sfnT $target $link_name
  end
end

set cwd (pwd)

# Home directory files
for file in (ls "$cwd/home")
  link "$cwd/home/$file" "$HOME/.$file"
end

# Config directories
for file in (ls "$cwd/config")
  link "$cwd/config/$file" "$HOME/.config/$file"
end

# Fonts
link "$cwd/fonts" "$HOME/.local/share/fonts"
